version: '3.4'

services:
  mvcdocker:
    image: ${DOCKER_REGISTRY-}mvcdocker
    build:
      context: .
      dockerfile: MVCDocker/Dockerfile
  database:
    container_name: MVCDocker_DB
    build:
      context: .
      dockerfile: Database/Dockerfile
    environment:
      SA_PASSWORD: "101MyPass101"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"